POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWludGVzdCIsImlkIjoiZGVkNjk4ZWMtYWRkZC00ODc3LThjMGMtYzEzZGI1YTE2YTY5IiwiaWF0IjoxNzIzMDE3Mzg1fQ.EFRMwlInL_ee2u8_dkUCL-w4uRc6WYUvAJl--bE90kw

{
  "title": "My first post",
  "content": "Hello world!"
}