POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWludGVzdCIsImlkIjoiYjAzZTU1YjUtMTRhNS00NGNkLWJkZDgtZTQ5MTM4MzE0ZDIwIiwiaWF0IjoxNzIzMDk0OTIxfQ.JKfnVoU8sgyzvGjfS1YJw5HcKzu44NXoCbeb0Gq7dDI 
 
{
  "title": "My first post",
  "content": "Hello world!"
}