/**
 * @description: This file contains the notifications reducer
 * which is responsible for handling the notifications state in the redux store.
 * The notifications reducer is responsible for handling the following actions:
 * 1. SET_NOTIFICATIONS: This action is dispatched when the notifications generated by the application
 * 2. CLEAR_NOTIFICATIONS: This action is dispatched when the notifications are cleared from the redux store.
 */

import { createSlice } from '@reduxjs/toolkit'

const notificationsSlice = createSlice({
  name: 'notifications',
  initialState: {
    message: null,
    type: null,
  },
  reducers: {
    setNotification(state, action) {
      return action.payload
    },
    clearNotification(state) {
      return {
        message: null,
        type: null,
      }
    }
  }
})

export const { setNotification, clearNotification } = notificationsSlice.actions
export default notificationsSlice.reducer